IPR/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.views.generic.base import RedirectView

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'IPR.views.home', name='home'),
    url(r'^favicon.ico$', RedirectView.as_view(url='/media/img/favicon_pnk.ico', permanent=True), name='favicon'),

    url(r'^simplimg/', include('simplimg.urls')),
    url(r'^olymp/', include('olymp.urls')),
    url(r'^edu/', include('education_programmes.urls')),
#    url(r'^mail/recovery/request/?$', 'IPR.views.mail_recovery_request',  name='mail-example-recovery-request'),
#    url(r'^mail2/?$', 'IPR.views.mail2',  name='mail-example-to'),
    url(r'^mail/?$', 'IPR.views.mail',  name='mail-example'),
    url(r'^mail2/?$', 'IPR.views.mail2',  name='mail-example-to'),

    url(r'^abc/?$', 'IPR.views.abc',  name='abc'),
    url(r'^abc2/?$', 'IPR.views.abc2',  name='abc-to'),

    url(r'^auth/notifications/?$', 'IPR.views.notifications',  name='notifications'),
    url(r'^auth/', include('common_user.urls')),
    #url(r'^todo/', include('todo.urls')),
    url(r'^msg/',include('user_messages.urls')),
	url(r'^ajax/region/statistic/(?P<raphael_slug>\w+)/?$','IPR.views.region_statistic', name='ajax_region_statistic'),

    url(r'^ajax/regions/?$','education_programmes.views.get_regions', name='ajax_get_regions'),
    url(r'^ajax/cities/?$','education_programmes.views.get_cities', name='ajax_get_cities'),
    url(r'^ajax/programs/?$','education_programmes.views.get_programm', name='ajax_get_programms'),
    url(r'^ajax/institutes/$','education_programmes.views.get_university', name='ajax_get_unvirsity_by_programm'),
    url(r'^ajax/has_seminar/$','education_programmes.views.get_seminar_attribute', name='ajax_seminar_attribute'),

    url(r'^archive/regions/?$',  'IPR.views.archive',  {'_type':'region'},    name='archive_regions'),
    url(r'^archive/cities/?$',   'IPR.views.archive',  {'_type':'city'},      name='archive_cities'),
    url(r'^archive/programs/?$', 'IPR.views.archive',  {'_type':'program'},   name='archive_programs'),
    url(r'^archive/institutes/$','IPR.views.archive',  {'_type':'institute'}, name='archive_unvirsity'),
    url(r'^archive/groups/$',    'IPR.views.archive',  {'_type':'group'},     name='archive_groups'),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/?', include(admin.site.urls)),
    url(r'^media/(?P<path>.*)$','django.views.static.serve', {'document_root': settings.PROJECT_ROOT + '/media/'}),
#    url(r'^favicon.ico$', RedirectView.as_view(url=settings.PROJECT_ROOT + '/media/images/favicon.ico')),

    url(r'^(?P<slug>[-\w\.]+)/?$','education_programmes.views.common_text', name='common-text-view'),
)

todo/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls.defaults import *
from django.conf import settings

urlpatterns = patterns('',
    #    url(r'^register/?$','common_user.views.register', name='register'),
    url(r'^list/?$','todo.views.list',name='todo_tasks_list'),
    url(r'^projects_list/?$','todo.views.projects_list',name='todo_projects_list'),
    url(r'^details/(?P<task_id>\d+)/?$','todo.views.details',name='todo_task_details'),
    url(r'^edit/(?P<task_id>\d+)/?$','todo.views.edit',name='todo_edit_task'),
    url(r'^add_task/?$','todo.views.add_task',name='todo_add_task'),
    url(r'^delete/(?P<task_id>\d+)/?$','todo.views.delete',name='todo_delete_task'),
    url(r'^project_details/(?P<project_id>\d+)/?$','todo.views.project_details',name='todo_project_details'),
    url(r'^delete_project_attach/(?P<attach_id>\d+)/?$','todo.views.delete_project_attach',name='todo_delete_project_attach'),
    url(r'^delete_task_attach/(?P<attach_id>\d+)/?$','todo.views.delete_task_attach',name='todo_delete_task_attach'),
    url(r'^add_project/?$','todo.views.add_project',name='todo_add_project'),
    url(r'^edit_project/(?P<project_id>\d+)/?$','todo.views.edit_project',name='todo_edit_project'),
    url(r'^delete_project/(?P<project_id>\d+)/?$','todo.views.delete_project',name='todo_delete_project'),
    url(r'^task_to_accepted/(?P<task_id>\d+)/?$','todo.views.task_to_accepted',name='todo_task_to_accepted'),
    url(r'^task_to_done/(?P<task_id>\d+)/?$','todo.views.task_to_done',name='todo_task_to_done'),
    url(r'^task_to_checked/(?P<task_id>\d+)/?$','todo.views.task_to_checked',name='todo_task_to_checked'),
    url(r'^task_to_new/(?P<task_id>\d+)/?$','todo.views.task_to_new',name='todo_task_to_new'),
    url(r'^add_comment/(?P<task_id>\d+)/?$','todo.views.add_comment',name='todo_add_comment'),
    url(r'^del_comment/(?P<comment_id>\d+)/?$','todo.views.del_comment',name='todo_del_comment'),
    url(r'^json_project_users/?$','todo.views.del_comment',name='todo_json_project_users'),
    url(r'^forbidden/?$','todo.views.forbidden',name='todo_forbidden'),
)

todo/models.py
# -*- coding: utf-8 -*-
#------------------------------------------------------------
# opentodo (c) 2009 Mikhail Grigoriev <mgrigoriev@gmail.com>
#
# This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty
# of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <http://www.gnu.org/licenses/>.
#------------------------------------------------------------

from django.db import models
from django.db.models import Q
#from django.contrib.auth.models import User
from common_user.models import  User


# Для уведомлений по e-mail
from django.template.loader import get_template
from django.template import Context
from django.conf import settings
from django.core.mail import EmailMessage

# Тема письма при изменении статуса задачи
TASK_NOTIF_SUBJECTS = {
    1: 'Новая задача',
    2: 'Задача принята на выполнение',
    3: 'Задача выполнена',
    4: 'Результат выполнения задачи одобрен',
    5: 'Задача открыта заново'
}

#---------------------------------------------------

# Удаляет дублирующие значения из списка
def uniqs(seq):
    return dict(zip(seq, [None,]*len(seq))).keys()

# Отправка почты - обертка для EmailMessage
def send_emails(subject, message, recipient_list):
    msg = EmailMessage(subject, message, settings.EMAIL_ADDRESS_FROM, recipient_list)
    msg.content_subtype = "html"
    msg.send(fail_silently=settings.EMAIL_FAIL_SILENTLY)

# Генерирует upload path для FileField
def make_upload_path(instance, filename):
    upload_path = "uploads"
    if isinstance(instance, ProjectAttach):
        project_id = instance.project.id
        return u"%s/%s/%s" % (upload_path, project_id, filename)

    elif isinstance(instance, TaskAttach):
        project_id = instance.task.project.id
        return u"%s/%s/tasks/%s" % (upload_path, project_id, filename)

# Пользователи в проектах
def users_in_projects(projects):
    users = User.objects.filter(
            Q(avail_projects__in=projects) | Q(is_admin=True)).distinct().order_by('first_name', 'last_name')
    return users

#---------------------------------------------------
# Модели

# Проекты
class ProjectManager(models.Manager):
    # Проекты, доступные для пользователя
    def available_for(self, user):
        if user.is_admin:
            return self.all().order_by('title')
        else:
            return user.avail_projects.all().order_by('title')     

class Project(models.Model):
    title = models.CharField("Проект", max_length=255)
    info = models.TextField("Описание", null=True, blank=True)
    created_at = models.DateTimeField("Дата добавления", auto_now_add=True)
    author = models.ForeignKey(User, null=True, db_column='author', related_name="projects", verbose_name="Автор")
    users = models.ManyToManyField(User, blank=True, null=True, verbose_name="Команда", related_name="avail_projects")
    objects = ProjectManager()

    def __unicode__(self):
        return self.title
    def _get_tasks_count(self):
        return self.related_tasks.count()
    def _get_tasks_count_active(self):
        return self.related_tasks.exclude(status=3).exclude(status=4).count()
    tasks_count = property(_get_tasks_count)
    tasks_active_count = property(_get_tasks_count_active)

    # Проект доступен для пользователя
    def is_avail(self, user):
        if user.is_admin:
            return True
        try:
            user.avail_projects.get(pk=self.pk)
            return True
        except Project.DoesNotExist:
            return False

    # Пользователи, имеющие доступ к проекту
    def allowed_users(self):
        pass

    # При добавлении проекта добавляем автора в команду
    def save(self):
        is_new = self._get_pk_val() is None
        super(Project, self).save()
        if is_new:
            self.users.add(self.author)

    class Meta:
        verbose_name = "проект"
        verbose_name_plural = "проекты"

# Статусы задач
class Status(models.Model):
    title = models.CharField("Статус", max_length=50)
    def __unicode__(self):
        return self.title

# Задачи
class Task(models.Model):
    project = models.ForeignKey(Project, verbose_name="Проект", related_name="related_tasks")
    status = models.ForeignKey(Status, default=1, verbose_name="Статус")
    author = models.ForeignKey(User, null=True, db_column='author', related_name="tasks", verbose_name="Автор")
    assigned_to = models.ForeignKey(User, null=True, db_column='assigned_to', related_name="assigned_tasks", verbose_name="Ответственный")
    created_at = models.DateTimeField("Дата добавления", auto_now_add=True)
    title =  models.CharField("Задача", max_length=255)
    info = models.TextField("Описание", null=True, blank=True)
    deadline = models.DateField("Срок", null=True, blank=True)
    has_deadline = models.BooleanField(default=0)
    def __unicode__(self):
        return self.title

    # Уведомления по e-mail (о добавлении задачи, изменении статуса)
    def mail_notify(self, host='', reopened=False):
        if settings.SEND_EMAILS:
            tmpl = get_template('todo/mail/task.html')
            msg_body = tmpl.render( Context({'t':self, 'host':host}) )
            addr = ''
            if reopened:
                notif_id = 5
            else:
                notif_id = self.status.id

            if ( notif_id in (1,4,5) ) and self.assigned_to.email:
                addr = self.assigned_to.email
            elif self.author.email:
                addr = self.author.email
        
            if addr:
                send_emails('[opentodo] '+TASK_NOTIF_SUBJECTS[notif_id], msg_body, [addr])
        
# Комментарии к задачам
class Comment(models.Model):
    task = models.ForeignKey(Task, related_name="comments")
    author = models.ForeignKey(User)
    message = models.TextField("Комментарий")
    created_at = models.DateTimeField("Дата", auto_now_add=True)
    reply_to = models.ForeignKey('self', null=True, blank=True)
    class Meta:
        ordering = ['created_at']

    # Уведомление по e-mail о добавлении комментария
    def mail_notify(self, host=''):
        if settings.SEND_EMAILS:
            tmpl = get_template('todo/mail/comment.html')
            msg_body = tmpl.render( Context({'t':self.task, 'c':self, 'host':host}) )
            addrs = []
            if self.task.author.email:
                addrs.append(self.task.author.email)
            if self.task.assigned_to and self.task.assigned_to.email:
                addrs.append(self.task.assigned_to.email)
            if self.reply_to and self.reply_to.author.email:
                addrs.append(self.reply_to.author.email)
            if addrs:
                send_emails('[opentodo] Комментарий к задаче', msg_body, uniqs(addrs))

# Абстрактный класс для файлов-вложений
class CommonAttach(models.Model):
    author = models.ForeignKey(User)
    created_at = models.DateTimeField(auto_now_add=True)
    attached_file = models.FileField(upload_to=make_upload_path)
    class Meta:
        abstract=True

# Аттачи к проектам
class ProjectAttach(CommonAttach):
    project = models.ForeignKey(Project, related_name="files")

# Аттачи к задачам
class TaskAttach(CommonAttach):
    task = models.ForeignKey(Task, related_name="files")

    # Уведомление по e-mail о прикреплении файла к задаче
    def mail_notify(self, host=''):
        if settings.SEND_EMAILS:
            tmpl = get_template('todo/mail/file.html')
            msg_body = tmpl.render( Context({'t':self.task, 'a':self, 'host':host}) )
            addrs = []
            if self.task.author.email:
                addrs.append(self.task.author.email)
            if self.task.assigned_to and self.task.assigned_to.email:
                addrs.append(self.task.assigned_to.email)
            
            if addrs:
                send_emails('[opentodo] Файл прикреплен к задаче', msg_body, uniqs(addrs))

todo/forms.py
# -*- coding: utf-8 -*-
#------------------------------------------------------------
# opentodo (c) 2009 Mikhail Grigoriev <mgrigoriev@gmail.com>
#
# This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty
# of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <http://www.gnu.org/licenses/>.
#------------------------------------------------------------

from django.forms import ModelForm
from django import forms
from todo.models import *
from common_user.models import  User
from todo.templatetags.todo_extras import username

class OpentodoModelForm(ModelForm):
    class Media:
        css = { 'all': ('forms.css',) }
        js = ('jquery.formvalidation.1.1.5.js',)

# Форма редактирования проекта
class ProjectForm(OpentodoModelForm):
    def __init__(self, *args, **kwargs):
        super(ProjectForm, self).__init__(*args, **kwargs)
        user_choices = []
        user_list = User.objects.filter(is_admin=True).order_by('first_name', 'last_name')
        for item in user_list:
            user_choices.append((item.id, username(item)))
        self.fields['users'].choices = user_choices

    title = forms.CharField(widget=forms.Textarea)
    class Meta:
        model = Project
        fields = ('title', 'info', 'users')

# Форма редактирования задачи
class TaskForm(OpentodoModelForm):
    def __init__(self, user, *args, **kwargs):
        super(TaskForm, self).__init__(*args, **kwargs)
        self.fields['project'].queryset = Project.objects.available_for(user)

    title = forms.CharField(widget=forms.Textarea)
    class Meta:
        model = Task
        fields = ('project', 'title', 'info', 'deadline')
    class Media:
        css = { 'all': ('ui.datepicker.css',) }
        js = ('ui.datepicker.js',)

# Форма загрузки файлов для проектов
class ProjectAttachForm(OpentodoModelForm):
    class Meta:
        model = ProjectAttach
        fields = ('attached_file',)

# Форма загрузки файлов для задач
class TaskAttachForm(OpentodoModelForm):
    class Meta:
        model = TaskAttach
        fields = ('attached_file',)

templates/todo/file_actions.html
{% load todo_extras %}

{% ifequal menu_active 'tasks' %}
<a href="javascript:if(confirm('Удалить файл {{a.attached_file.path|attach}}?')) location.href='{% url "todo_delete_task_attach" a.id %}'" style="color:red;font-weight:normal"><img src="/media/opentodo_media/img/cross_small.gif" alt="" width="16" height="16" title="удалить" /></a>
{% else %}{% ifequal menu_active 'projects' %}
<a href="javascript:if(confirm('Удалить файл {{a.attached_file.path|attach}}?')) location.href='{% url "todo_delete_project_attach" a.id %}'" style="color:red;font-weight:normal"><img src="/media/opentodo_media/img/cross_small.gif" alt="" width="16" height="16" title="удалить" /></a>
{% endifequal %}{% endifequal %}

templates/todo/json_project_users.html
{% load todo_extras %}
[
{optionValue:'', optionDisplay: '---------'},
{% for user in users %}
{optionValue:{{user.id}}, optionDisplay: '{{user|username}}'}{% if not forloop.last %}, {% endif %}
{% endfor %}
]

templates/todo/project_actions.html
<br /><a href="{% url "todo_edit_project" project.id %}"><img src="/media/opentodo_media/img/pencil.gif" alt="" width="16" height="16" title="редактировать" /></a>&nbsp;&nbsp;<a href="javascript:if(confirm('Удалить проект {{project.title}}?')) location.href='{% url "todo_delete_project" project.id %}'" style="color: red"><img src="/media/opentodo_media/img/cross.gif" alt="" width="16" height="16" title="удалить" /></a>

templates/todo/project_delete_cannot.html
{% extends "todo.html" %}
{% load todo_extras %}

{% block title %}Нельзя удалить проект "{{project}}"{% endblock %}

{% block left %}
<a href={% url projects_list %}>&larr; Назад к проектам</a>
{% endblock %}

{% block content %}
<big>Проект <a href="{% url "todo_project_details" project.id %}">{{ project.title }}</a> содержит задачи ({{project.tasks_count}}), поэтому его нельзя удалить<big>.
{% endblock %}

templates/todo/project_details.html
{% extends "todo.html" %}
{% load todo_extras %}

{% block extra_media %}
{{f.media}}
{% include "extra_css.html" %}
{% endblock %}

{% block title %}{{project}}{% endblock %}

{% block left %}

<div>
<b>Автор</b><br />
<span>{{project.author|username}}</span>
</div>
<div class="top-indent">
<b>Дата создания</b><br />
<span>{{project.created_at|format_date:"short"}}</span>
</div>
{% if user.is_admin %}
	{% include "todo/project_actions.html" %}
{% endif %}

{% endblock %}

{% block content %}
<div id="task-container" style="padding-bottom:0">
<h2 id="task-title">{{project.title}}</h2>
{% if project.info %}
<div id="task-info">{{project.info|sanitize}}</div>
<div style="color:#000; padding: 5px 0">
<b>Участники:</b> {% for member in project.users.all %}{{member|username}}{% if not forloop.last %}, {% endif %}{% endfor %}
</div>
{% endif %}

<div id="task-action">
<a href="{% url "todo_tasks_list" %}?project_id={{project.id}}&folder=all" class="bigger"><i>Задачи проекта</i></a>
({{project.tasks_count}}{%if project.tasks_active_count%}, <b>{{project.tasks_active_count}}</b>{% endif %})
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<a href="{% url "todo_projects_list" %}" class="bigger">Назад к списку проектов</a>
</div>
</div>

<a name="files"></a>
{% include "todo/files.html" %}

{% endblock %}

templates/todo/project_form.html
<script type="text/javascript"> 
$(document).ready(function(){
	$("#id_title").attr("required", "true");
	$("#id_deadline").attr("mask", "datemask");
	
	$('#projectform').formValidation({
		err_class: "invalidInput",
		display_alert: false
	});
});
</script> 

<div class="formErrors">
	{% if form.title.errors %}Не введено название проекта<br />{% endif %}
</div>

<div class="editformWrapper" style="width:800px">
<form method="post" id="editform">
	<table id="editform_table" cellspacing="0">
	<tr>
		<th><label for="id_title"><span class="red">*</span> Проект:</label></th>
		<td>{{form.title}}</td>
	</tr>
	<tr>
		<th style="padding-top: 30px"><label for="id_info">Описание:</label></th>
		<td>{% include "todo/wysiwyg.html" %} {{form.info}}</td>
	</tr>
	<tr>
		<th style="width:180px"><span class="red">*</span> <label for="id_users">Пользователи:</label><br /><span style="color:#999">(aдминистраторы имеют доступ в любом случае)</span></th>
		<td>{{form.users}}</td>
	</tr>
	<tr>
		<th></th>
		<td style="padding-top:10px"><input type="submit" value="Сохранить" class="button" /><a href="{% if add %}{% url "todo_projects_list" %}{% else %}{% url "todo_project_details" project.id %}{% endif %}">отмена</a></td>
	</tr>
	</table>
</form>
</div>

{% if add %}
<script language="javascript">
	document.getElementById('id_title').focus();
</script>
{% endif %}

templates/todo/task_details.html
{% extends "todo.html" %}
{% load todo_extras %}

{% block extra_media %}
{{f.media}}
{% include "extra_css.html" %}
{% endblock %}

{% block title %}{{task}}{% endblock %}


{% block left %}

<div>
<b>Проект</b><br />
<span><a href="{% url "todo_project_details" task.project.id %}">{{task.project.title}}</a></span>
</div>

<div class="top-indent">
<b>Автор</b><br />
<span>{{task.author|username}}</span>
</div>

<div class="top-indent">
<b>Добавлена</b><br />
<span>{{task.created_at|format_date:"short"}}</span>
</div>

<div class="top-indent">
<b>Ответственный</b><br />
{% if task.assigned_to %}
<span>{{task.assigned_to|username}}</span>
{% else %}
<span>не назначен</span>
{% endif %}
</div>

{% if task.deadline %}
<div class="top-indent">
<b>Срок</b><br />
<span>{{task.deadline|format_deadline:task.status.id}}</span>
</div>
{% endif %}

{% ifequal task.author user %}
	{% include "todo/task_actions.html" %}
{% else %}
	{% if perms.todo.change_task %}
		{% include "todo/task_actions.html" %}
	{% endif %}
{% endifequal %}

{% endblock %}


{% block content %}
<div id="task-container">

<h2 id="task-title">{{task.title}}</h2>
{% if task.info %}<div id="task-info">{{task.info|sanitize}}</div>{% endif %}
</div>

<div id="task-action">

<table cellpadding="0" cellspacing="0" border="0"><tr>
<td style="vertical-align:middle;padding-left:0px">
<div class="status status{{task.status.id}}" style="display:inline">&nbsp;{% ifequal task.status.id 4 %}завершена{% else %}{{task.status.title|lower}}{% endifequal %}&nbsp;</div>
</td>

<td style="padding-left:10px">

{% ifequal task.status.id 1 %}
	{% ifequal task.assigned_to.id user.id %}
		<a class="button" href="{% url "todo_task_to_accepted" task.id %}"><span>Принять</span></a>
	{% else %}&nbsp;{% endifequal %}
{% endifequal %}
{% ifequal task.status.id 2 %}
	{% ifequal task.assigned_to.id user.id %}
		<a class="button" href="{% url "todo_task_to_done" task.id %}"><span>Завершить</span></a>
	{% else %}&nbsp;{% endifequal %}
{% endifequal %}
{% ifequal task.status.id 3 %}
	{% ifequal task.author.id user.id %}
		<a class="button" href="{% url "todo_task_to_checked" task.id %}"><span><b>Одобрить</b></span></a><a class="button" href="{% url "todo_task_to_new" task.id %}"><span>Открыть&nbsp;заново</span></a>
	{% else %}&nbsp;{% endifequal %}
{% endifequal %}
{% ifequal task.status.id 4 %}
	{% ifequal task.author.id user.id %}
		<a class="button" href="{% url "todo_task_to_new" task.id %}"><span>Открыть&nbsp;заново</span></a>
	{% else %}&nbsp;{% endifequal %}
{% endifequal %}

</td>
<td style="vertical-align:middle;padding-left:50px"><a href="{% url "todo_tasks_list" %}" class="bigger">Назад к списку задач</a></td>
</tr></table>

</div>


<div id="task-extra">

<a name="files"></a>
{% include "todo/files.html" %}

<a name="comments"></a>
{% include "todo/task_comments.html" %}

</div>

{% endblock %}

templates/todo/task_form.html
{% load todo_extras %}
<script type="text/javascript"> 
$(document).ready(function(){
	load_users();

	$('#id_deadline').attachDatepicker({showOn:'both', buttonImage:'/media/opentodo_media/img/calendar.gif', buttonImageOnly:true});

	$("#id_project").attr("required", "true");
	$("#id_title").attr("required", "true");
	$("#id_deadline").attr("mask", "datemask");
	
	$('#editform').formValidation({
		err_class: "invalidInput",
		display_alert: false,
		datemask : /[0-9]{4}-[0-9]{2}-[0-9]{2}/
	});

	$("select#id_project").change(function(){
		load_users();
	});
});

function load_users() {
	$.getJSON("{% url "todo_json_project_users" %}",{id: $('#id_project :selected').val(), ajax: 'true'}, function(j){
		$("#loader").show();

		selected_id = {% if add %}{{user.id}}{% else %}{{task.assigned_to.id}}{% endif %}

		var options = '';
		for (var i = 0; i < j.length; i++) {
			options += '<option value="' + j[i].optionValue + '"';
			if (j[i].optionValue == selected_id) {
				options += ' selected="selected"';
			}
			options += '>' + j[i].optionDisplay + '</option>';
		}
		$("select#id_assigned_to").html(options);
		setTimeout(function() { $("#loader").hide(); }, 300);
	})
}
</script>

<div class="formErrors">
	{% if form.project.errors %}Не выбран проект<br />{% endif %}
	{% if form.title.errors %}Не введена задача<br />{% endif %}
	{% if form.deadline.errors %}Формат даты в поле Срок должен быть yyyy-mm-dd<br />{% endif %}
</div>

<div class="editformWrapper" style="width:780px;">
<form method="post" id="editform">
	<table id="editform_table" cellspacing="0">
	<tr>
		<th><label for="id_project"><span class="red">*</span> Проект:</label></th>
		<td>{{form.project}}</td>
	</tr>
	<tr>
		<th><label for="id_title"><span class="red">*</span> Задача:</label></th>
		<td>{{form.title}}</td>
	</tr>
	<tr>
		<th style="padding-top: 30px"><label for="id_info">Описание:</label></th>
		<td>
		{% include "todo/wysiwyg.html" %}
		{{form.info}}</td>
	</tr>
	<tr>
		<th><label for="id_deadline">Срок:</label></th>
		<td>{{form.deadline}}</td>
	</tr>
	<tr>
		<th><label for="id_assigned_to">Ответственный:</label></th>
		<td>
		<select name="assigned_to" id="id_assigned_to"> 
		<option value="" selected="selected">---------</option>
	{% for u in users %}
		<option value="{{u.id}}"{% if add %}{% ifequal u.id user.id %} selected="selected"{% endifequal %}{% else %}{% ifequal u.id task.assigned_to.id %} selected="selected"{% endifequal %}{% endif %}>{{u|username}}</option> 
	{% endfor %}
		</select><img src="/media/opentodo_media/img/ajax-loader.gif" id="loader" style="padding-left:5px; display:none" />
		</td>
	</tr>
	<tr>
		<th>&nbsp;</th>
		<td style="padding-top:15px"><input type="submit" value="Сохранить задачу" class="button" /><a href="{% if add %}{% url "todo_tasks_list" %}{% else %}{% url "todo_task_details" task.id %}{% endif %}">отмена</a></td>
	</tr>
	</table>
</form>
</div>

{% if add %}
<script language="javascript">
if (document.getElementById('id_project').selectedIndex > 0) {
	document.getElementById('id_title').focus();
}
</script>
{% endif %}