IPR/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.views.generic.base import RedirectView

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'IPR.views.home', name='home'),
    url(r'^favicon.ico$', RedirectView.as_view(url='/media/img/favicon_pnk.ico', permanent=True), name='favicon'),

    url(r'^simplimg/', include('simplimg.urls')),
    url(r'^olymp/', include('olymp.urls')),
    url(r'^edu/', include('education_programmes.urls')),
#    url(r'^mail/recovery/request/?$', 'IPR.views.mail_recovery_request',  name='mail-example-recovery-request'),
#    url(r'^mail2/?$', 'IPR.views.mail2',  name='mail-example-to'),
    url(r'^mail/?$', 'IPR.views.mail',  name='mail-example'),
    url(r'^mail2/?$', 'IPR.views.mail2',  name='mail-example-to'),

    url(r'^abc/?$', 'IPR.views.abc',  name='abc'),
    url(r'^abc2/?$', 'IPR.views.abc2',  name='abc-to'),

    url(r'^auth/notifications/?$', 'IPR.views.notifications',  name='notifications'),
    url(r'^auth/', include('common_user.urls')),
    #url(r'^todo/', include('todo.urls')),
    url(r'^msg/',include('user_messages.urls')),
	url(r'^ajax/region/statistic/(?P<raphael_slug>\w+)/?$','IPR.views.region_statistic', name='ajax_region_statistic'),

    url(r'^ajax/regions/?$','education_programmes.views.get_regions', name='ajax_get_regions'),
    url(r'^ajax/cities/?$','education_programmes.views.get_cities', name='ajax_get_cities'),
    url(r'^ajax/programs/?$','education_programmes.views.get_programm', name='ajax_get_programms'),
    url(r'^ajax/institutes/$','education_programmes.views.get_university', name='ajax_get_unvirsity_by_programm'),
    url(r'^ajax/has_seminar/$','education_programmes.views.get_seminar_attribute', name='ajax_seminar_attribute'),

    url(r'^archive/regions/?$',  'IPR.views.archive',  {'_type':'region'},    name='archive_regions'),
    url(r'^archive/cities/?$',   'IPR.views.archive',  {'_type':'city'},      name='archive_cities'),
    url(r'^archive/programs/?$', 'IPR.views.archive',  {'_type':'program'},   name='archive_programs'),
    url(r'^archive/institutes/$','IPR.views.archive',  {'_type':'institute'}, name='archive_unvirsity'),
    url(r'^archive/groups/$',    'IPR.views.archive',  {'_type':'group'},     name='archive_groups'),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/?', include(admin.site.urls)),
    url(r'^media/(?P<path>.*)$','django.views.static.serve', {'document_root': settings.PROJECT_ROOT + '/media/'}),
#    url(r'^favicon.ico$', RedirectView.as_view(url=settings.PROJECT_ROOT + '/media/images/favicon.ico')),

    url(r'^(?P<slug>[-\w\.]+)/?$','education_programmes.views.common_text', name='common-text-view'),
)

todo/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls.defaults import *
from django.conf import settings

urlpatterns = patterns('',
    #    url(r'^register/?$','common_user.views.register', name='register'),
    url(r'^list/?$','todo.views.list',name='todo_tasks_list'),
    url(r'^projects_list/?$','todo.views.projects_list',name='todo_projects_list'),
    url(r'^details/(?P<task_id>\d+)/?$','todo.views.details',name='todo_task_details'),
    url(r'^edit/(?P<task_id>\d+)/?$','todo.views.edit',name='todo_edit_task'),
    url(r'^add_task/?$','todo.views.add_task',name='todo_add_task'),
    url(r'^delete/(?P<task_id>\d+)/?$','todo.views.delete',name='todo_delete_task'),
    url(r'^project_details/(?P<project_id>\d+)/?$','todo.views.project_details',name='todo_project_details'),
    url(r'^delete_project_attach/(?P<attach_id>\d+)/?$','todo.views.delete_project_attach',name='todo_delete_project_attach'),
    url(r'^delete_task_attach/(?P<attach_id>\d+)/?$','todo.views.delete_task_attach',name='todo_delete_task_attach'),
    url(r'^add_project/?$','todo.views.add_project',name='todo_add_project'),
    url(r'^edit_project/(?P<project_id>\d+)/?$','todo.views.edit_project',name='todo_edit_project'),
    url(r'^delete_project/(?P<project_id>\d+)/?$','todo.views.delete_project',name='todo_delete_project'),
    url(r'^task_to_accepted/(?P<task_id>\d+)/?$','todo.views.task_to_accepted',name='todo_task_to_accepted'),
    url(r'^task_to_done/(?P<task_id>\d+)/?$','todo.views.task_to_done',name='todo_task_to_done'),
    url(r'^task_to_checked/(?P<task_id>\d+)/?$','todo.views.task_to_checked',name='todo_task_to_checked'),
    url(r'^task_to_new/(?P<task_id>\d+)/?$','todo.views.task_to_new',name='todo_task_to_new'),
    url(r'^add_comment/(?P<task_id>\d+)/?$','todo.views.add_comment',name='todo_add_comment'),
    url(r'^del_comment/(?P<comment_id>\d+)/?$','todo.views.del_comment',name='todo_del_comment'),
    url(r'^json_project_users/?$','todo.views.del_comment',name='todo_json_project_users'),
    url(r'^forbidden/?$','todo.views.forbidden',name='todo_forbidden'),
)

people/forms.py
# -*- coding: utf-8 -*-

from django import forms
from django.core import validators
from django.db.models import Q,Avg, Max, Min
from django.forms import ModelForm, Textarea
from django.forms.extras import * #SelectDateWidget
from models import *
from common_user.models import User
import sys,datetime

from django.conf import settings
from olymp.widgets import *

    
class UniversityRegisterForm(ModelForm):
    username  = forms.CharField(max_length=75, label=u'Логин')
    password1 = forms.CharField(widget=forms.PasswordInput,label=u'Пароль')
    password2 = forms.CharField(widget=forms.PasswordInput,label=u'Подтвердите пароль')
    
    class Meta:
        model = University
        fields = ['name','username','password1','password2','region','city','email','phone','rector_last_name','rector_first_name','rector_patronymic','curator_last_name','curator_first_name','curator_patronymic','curator_position']

    def clean(self):

        username = self.cleaned_data['username']

        if User.objects.filter(username=username).count():
            self._errors["username"] = self.error_class([u"пользователь с таким логином уже существует"])


        if (self.cleaned_data.get("password2", "") != self.cleaned_data.get("password1", "")):
            self._errors["password1"] = self.error_class([u"Пароли не совпадают."])
            #raise forms.ValidationError(u"Пароли не совпадают.")

        try:
            validators.validate_email(self.cleaned_data["email"])
        except:
            self._errors["email"] = self.error_class([u'Проверьте правильность ввода e-mail.'])

        return self.cleaned_data

class UniversityEditForm(ModelForm):
    class Meta:
        model = University
        fields = ['name','region','city','email','phone','rector_first_name','rector_last_name','rector_patronymic','curator_first_name','curator_last_name','curator_patronymic','curator_position']

    def clean(self):
        try:
            validators.validate_email(self.cleaned_data["email"])
        except:
            self._errors["email"] = self.error_class([u'Проверьте правильность ввода e-mail.'])

        return self.cleaned_data



#class StudentForm(ModelForm):
#    id                 = forms.IntegerField(required= False,label = u'ID')
#    must_delete        = forms.IntegerField(initial = 0,label = u'Удалить')
#    delete_checkbox    = forms.BooleanField(required= False,label=u'Удалить')
#
#    class Meta:
#        model = Question
#        fields = ['test','text','option1','option2','option3','option4','correct_option','number']
#
#        widgets = {
#            'test' : forms.HiddenInput(),
#            }
#
#    def __init__(self,*args, **kwargs):
#        super(QuestionForm, self).__init__(*args, **kwargs)
#        self.fields['must_delete'].widget = forms.HiddenInput()
#        self.fields['id'].widget = forms.HiddenInput()
#
#        if kwargs.has_key('instance'):
#            print  kwargs['instance'].id
#            self.fields['id'].initial = kwargs['instance'].id
#
#    def clean(self):
#        if self.cleaned_data.get("option1") == self.cleaned_data.get("option2"):
#            self._errors["option2"] = self.error_class([u'Вариант ответа не уникален!'])
#        if self.cleaned_data.get("option1") == self.cleaned_data.get("option3"):
#            self._errors["option3"] = self.error_class([u'Вариант ответа не уникален!'])
#        if self.cleaned_data.get("option1") == self.cleaned_data.get("option4"):
#            self._errors["option4"] = self.error_class([u'Вариант ответа не уникален!'])
#
#        if self.cleaned_data.get("option2") == self.cleaned_data.get("option3"):
#            self._errors["option3"] = self.error_class([u'Вариант ответа не уникален!'])
#        if self.cleaned_data.get("option2") == self.cleaned_data.get("option4"):
#            self._errors["option4"] = self.error_class([u'Вариант ответа не уникален!'])
#
#        if self.cleaned_data.get("option3") == self.cleaned_data.get("option4"):
#            self._errors["option4"] = self.error_class([u'Вариант ответа не уникален!'])
#        return self.cleaned_data



class OlympStudentShortForm(forms.Form):
    new_student_last_name          = forms.CharField(label = u'Фамилия', max_length=60)
    new_student_first_name           = forms.CharField(label = u'Имя', max_length=60)
    new_student_patronymic          = forms.CharField(label = u'Отчество', max_length=100)
    new_student_email               = forms.EmailField(label = u'Электронный адрес', max_length=100)
    new_student_birthday            = forms.DateField(label = u'Дата рождения')
    new_student_speciality          = forms.CharField(max_length=50,label = u'Направление')
    new_student_course              = forms.ChoiceField(choices=COURSE_CHOICES,label = u'Курс')
    new_student_finish_year         = forms.IntegerField(initial = 2014, label = u'Планируемый год выпуска')
    new_student_must_delete         = forms.IntegerField(initial = 0,label = u'Удалить')
    new_student_delete_checkbox     = forms.BooleanField(required= False,label=u'Удалить')

    def __init__(self,*args, **kwargs):
        super(OlympStudentShortForm, self).__init__(*args, **kwargs)
        self.fields['new_student_finish_year'].widget = forms.TextInput(attrs={'maxlength':4})
        self.fields['new_student_must_delete'].widget = forms.HiddenInput()
#        self.fields['new_student_birthday'].widget = DateWidget()


    def clean(self):
        try:
            validators.validate_email(self.cleaned_data["new_student_email"])
        except:
            self._errors["new_student_email"] = self.error_class([u'Проверьте правильность ввода e-mail.'])


#        if self.cleaned_data.get("new_question_option1") == self.cleaned_data.get("new_question_option2"):
#            self._errors["new_question_option2"] = self.error_class([u'Вариант ответа не уникален!'])
#        if self.cleaned_data.get("new_question_option1") == self.cleaned_data.get("new_question_option3"):
#            self._errors["new_question_option3"] = self.error_class([u'Вариант ответа не уникален!'])
#        if self.cleaned_data.get("new_question_option1") == self.cleaned_data.get("new_question_option4"):
#            self._errors["new_question_option4"] = self.error_class([u'Вариант ответа не уникален!'])
#
#        if self.cleaned_data.get("new_question_option2") == self.cleaned_data.get("new_question_option3"):
#            self._errors["new_question_option3"] = self.error_class([u'Вариант ответа не уникален!'])
#        if self.cleaned_data.get("new_question_option2") == self.cleaned_data.get("option4"):
#            self._errors["new_question_option4"] = self.error_class([u'Вариант ответа не уникален!'])
#
#        if self.cleaned_data.get("new_question_option3") == self.cleaned_data.get("new_question_option4"):
#            self._errors["new_question_option4"] = self.error_class([u'Вариант ответа не уникален!'])
        return self.cleaned_data


class OlympStudentForm(forms.ModelForm):
    id                 = forms.IntegerField(required= False,label = u'id')
    username           = forms.CharField(label = u'Логин', max_length=60)
    last_name         = forms.CharField(label = u'Фамилия', max_length=60)
    first_name          = forms.CharField(label = u'Имя', max_length=60)

    must_delete        = forms.IntegerField(initial = 0,label = u'Удалить')
    delete_checkbox    = forms.BooleanField(required= False,label=u'Удалить')

    class Meta:
        model = OlympStudent
        fields = ['user','id','username','detail','first_name','last_name','patronymic','email','birthday','speciality','course','finish_year']

        widgets = {
            'user' : forms.HiddenInput(),
            }

    def __init__(self,*args, **kwargs):
        super(OlympStudentForm, self).__init__(*args, **kwargs)
        self.fields['must_delete'].widget = forms.HiddenInput()
        self.fields['id'].widget = forms.HiddenInput()

        self.fields['username'].widget.attrs['readonly'] = True
        self.fields['detail'].widget.attrs['readonly'] = True

        if kwargs.has_key('instance'):
            print  kwargs['instance'].id
            self.fields['id'].initial = kwargs['instance'].id

            if kwargs['instance'].user is not None:
                self.fields['last_name'].initial = kwargs['instance'].user.last_name
                self.fields['first_name'].initial = kwargs['instance'].user.first_name
                self.fields['username'].initial = kwargs['instance'].user.username

    def clean(self):
        try:
            validators.validate_email(self.cleaned_data["email"])
        except:
            self._errors["email"] = self.error_class([u'Проверьте правильность ввода e-mail.'])

        return self.cleaned_data
		
class SoupForm(forms.Form):
    login = forms.CharField(max_length=30,label=u'Логин')
    password1 = forms.CharField(widget=forms.PasswordInput,label=u'Пароль')
    password2 = forms.CharField(widget=forms.PasswordInput,label=u'Подтвердите пароль')
    surname = forms.CharField(max_length=50,label=u'Фамилия')
    name = forms.CharField(max_length=50,label=u'Имя')

    def __init__(self, *args, **kwargs):
        super(SoupForm,self).__init__(*args, **kwargs)

    def clean(self):
        if (self.cleaned_data.get("password2", "") != self.cleaned_data.get("password1", "")):
            self._errors["password1"] = self.error_class([u"Пароли не совпадают."])
            raise forms.ValidationError(u"Пароли не совпадают.")

        try:
            login_exist = User.objects.get(username=self.cleaned_data["login"])
        except:
            login_exist = None
            #if email_exist is not None:
        if login_exist:
            self._errors["login"] = self.error_class([u'Такой пользователь уже зарегистрирован. Используйте другой, либо авторизуйтесь.'])
            raise forms.ValidationError(u'Такой пользователь уже зарегистрирован. Используйте другой, либо авторизуйтесь.')

todo/forms.py
# -*- coding: utf-8 -*-
#------------------------------------------------------------
# opentodo (c) 2009 Mikhail Grigoriev <mgrigoriev@gmail.com>
#
# This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty
# of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <http://www.gnu.org/licenses/>.
#------------------------------------------------------------

from django.forms import ModelForm
from django import forms
from todo.models import *
from common_user.models import  User
from todo.templatetags.todo_extras import username

class OpentodoModelForm(ModelForm):
    class Media:
        css = { 'all': ('forms.css',) }
        js = ('jquery.formvalidation.1.1.5.js',)

# Форма редактирования проекта
class ProjectForm(OpentodoModelForm):
    def __init__(self, *args, **kwargs):
        super(ProjectForm, self).__init__(*args, **kwargs)
        user_choices = []
        user_list = User.objects.filter(is_admin=True).order_by('first_name', 'last_name')
        for item in user_list:
            user_choices.append((item.id, username(item)))
        self.fields['users'].choices = user_choices

    title = forms.CharField(widget=forms.Textarea)
    class Meta:
        model = Project
        fields = ('title', 'info', 'users')

# Форма редактирования задачи
class TaskForm(OpentodoModelForm):
    def __init__(self, user, *args, **kwargs):
        super(TaskForm, self).__init__(*args, **kwargs)
        self.fields['project'].queryset = Project.objects.available_for(user)

    title = forms.CharField(widget=forms.Textarea)
    class Meta:
        model = Task
        fields = ('project', 'title', 'info', 'deadline')
    class Media:
        css = { 'all': ('ui.datepicker.css',) }
        js = ('ui.datepicker.js',)

# Форма загрузки файлов для проектов
class ProjectAttachForm(OpentodoModelForm):
    class Meta:
        model = ProjectAttach
        fields = ('attached_file',)

# Форма загрузки файлов для задач
class TaskAttachForm(OpentodoModelForm):
    class Meta:
        model = TaskAttach
        fields = ('attached_file',)

messages/views.py
# Create your views here.

templates/changepass_done.html
{% extends "index.html" %}

{% block jquery_ready %}

$("a#go_auth").click(function(){
    open_auth_block();
    scrollTo($(".popup__wrapper").top,$(".popup__wrapper").left);
    return false;
});

{% endblock %}

{% block content %}

      <div class="personal_card_header"><label>Авторизация</label></div>

      <div class="personal_card_content stretchable" type="personal">
        <h2>Уважаемый, {{ fio }} , вы успешно изменили пароль</h3>
        <h3>Для дальнейшей работы, пожалуйста, <a href="#" id="go_auth">авторизуйтесь</a></h3>
      </div>
{% endblock %}

templates/email_templateform.html
{% extends "personal_cabinet.html" %}

{% block include %}
<!--<script type="text/javascript" src="/media/tiny_mce/tiny_mce.js"></script>-->
<!--<script type="text/javascript">-->
    <!--tinyMCE.init({-->
        <!--mode: "textareas",-->
        <!--theme: "advanced",-->
        <!--plugins: "advhr,table,emotions,media,insertdatetime,directionality",-->
        <!--theme_advanced_toolbar_align: "left",-->
        <!--theme_advanced_toolbar_location: "top",-->
        <!--theme_advanced_buttons1:"bold,italic,underline,strikethrough,sub,sup,separator,justifyleft,justifycenter,justifyright,justifyfull,separator,formatselect,fontselect,fontsizeselect,forecolor",-->
        <!--theme_advanced_buttons2:"bullist,numlist,outdent,indent,ltr,rtl,separator,link,unlink,anchor,image,separator,table,insertdate,inserttime,advhr,emotions,media,charmap,separator,undo,redo",-->
        <!--theme_advanced_buttons3_add:"forecolor,backcolor",-->


        <!--theme_advanced_font_sizes:"170%,10px,11px,12px,13px,14px,15px,16px,17px,18px,19px,20px,21px,22px,23px,24px,25px,26px,27px,28px,29px,30px,32px,48px",-->
        <!--height: "350px",-->
        <!--width: "653px"-->
    <!--});-->
<!--</script>-->


{% endblock %}


{% block jquery_ready %}

{% endblock %}

{% block page_style %}
textarea{
        height: 500px !important;
        }
{% endblock %}

{% block urlpath %} {{ block.super }} / <a href="{% url "email-template-edit" template_name %}">{{ mailing_name }}</a> {% endblock %}

{% block caption %}
{% endblock %}

{% block slow_button_panel %}
{% endblock %}


{% block content %}
    {% if user.is_admin%}

	<div class="item">
      <div class="personal_card_header"><label>{{ mailing_name }}</label>
	  </div>
      <div class="personal_card_content stretchable">

      <form id="preview" action="{% url "email-template-preview" template_name %}" method="GET">
      </form>
	
	<form action="{% url "email-template-edit" template_name %}" method="POST" class="editform">
          {% csrf_token %}

        <div class="row">
            
        <section class="label">
            <label> Текст шаблона <span>*</span></label>
        </section>
        <textarea name="template_content"> {{ file_content }} </textarea>
        </div>

        <div class="row">

         <section class="label">
            <label> Html шаблон<span>*</span></label>
         </section>
         <textarea name="html_template_content"> {{ html_file_content }} </textarea>
        </div>

          <div class="row">

          <table class="button_panel">
              <tr>
                  <td><input type="submit" value="Сохранить" /></td>
                  <td><input type="submit" form="preview" value="Посмотреть" /></td>
              </tr>
          </table>
              </div>
        
		<!--<div class="row last">-->
            <!--<input type="submit" value="Сохранить" />-->
        <!--</div>-->
</form>
</div>
    </div>

  {% endif %}
{% endblock %}

{% block right_button_panel %}
{% endblock %}

templates/person_request.html
{% extends "personal_cabinet.html" %}

{% block jquery_ready %}
  
{% if level == 'U' %}
function change_seminar_fields(set_visible){

   var display = "none", python_bool = 'False';

   if( set_visible == true ){
     display = "block";
     python_bool = 'True';
   }else{

     $('#id_practic_period').val('');
     $('#id_payment_method').val('');
     $('#id_details').text('');

   }

   $('#id_practic_period').closest(".row").css("display",display);
   $('#id_payment_method').closest(".row").css("display",display);
   $('#id_has_seminar').val(python_bool);

   if( set_visible == true && $('#id_payment_method').val() == 'U' ){
     $('#id_details').closest(".row").css("display","block");
   }else{
     $('#id_details').closest(".row").css("display","none");
   }

}

function get_seminar_attribute(institute_id,program_id){

$.post('/ajax/has_seminar/',{institute: institute_id, program: program_id}, function (data) {
  change_seminar_fields(data);
});
  }

function add_required_star(identifier){
  var id_row = $(identifier).closest(".row"), id_label = id_row.find('label');
  id_label.text(id_label.text() + ' *');
}

   if ($('#id_has_seminar').val() == 'True'){
   change_seminar_fields(true);
   }else{
   change_seminar_fields(false);
   }

$('#id_payment_method').change(function(){

if( $('#id_payment_method').val() != 'U' ){
$('#id_details').closest(".row").css("display","none");
}else{
$('#id_details').closest(".row").css("display","block");
}
});

$('#id_education_institute').change(function(){

get_seminar_attribute($("#id_education_institute option:selected").val(), $("#id_education_program option:selected").val());

        });

$('#id_education_program').change(function(){

  get_seminar_attribute($("#id_education_institute option:selected").val(), $("#id_education_program option:selected").val());

});


  add_required_star('#id_practic_period');
  add_required_star('#id_payment_method');
  add_required_star('#id_details');
{% endif %}
{% endblock %}

{% block page_style %}

{% endblock %}

{% block include %}
<script type="text/javascript" src="/media/js/jquery-ui-1.8.18/development-bundle/ui/i18n/jquery.ui.datepicker-ru.js"></script>
<link rel="stylesheet" type="text/css" media="all" href="/media/css/cupertino/jquery-ui-1.8.18.custom.css" />

{% endblock %}

{% block urlpath %} {{ block.super }} / <a href="{% url 'search' %}">Поиск информации</a>  / <a href="{% url 'person-edit' person.slug %}">{{ person.get_fio }}</a> / <a href="{% url 'person-request' person.slug %}">Новое заявление</a> {% endblock %}

{% block caption %}
{% endblock %}

{% block slow_button_panel %}
{% endblock %}

{% block content %}

<div  class="item" id="profile_card">
    <h1>{{ person.get_fio }}. Новое заявление на {% if person.user.is_student %}подготовку{% endif %}{% if person.user.is_ipr %}повышение квалификации{% endif %}</h1>

    {% if user.is_admin %}
    <div class="personal_card_content stretchable" type="request">

        {% include 'errors_and_messages.html' %}
        <form id="requestform" action="" method="POST" class="editform" enctype="multipart/form-data">
            {% csrf_token %}
            <!--<input type="hidden" id="id_id" name="id" value="{{ item.id }}">-->

            {% include 'form_loop.html' with Form=RequestForm %}
            {% include 'form_loop.html' %}

            <div class="row last">
                <input type="submit" value="{% if item.id %}Изменить{% else %}Сохранить{% endif %}" />
            </div>

        </form>

                
    </div>
    {% endif %}
    <div class="clear"></div>
</div>
{% endblock %}

{% block right_button_panel %}
{% endblock %}

templates/program_item_in_catalog.html
<div class="slider_item institute_slider_item" item="programm_{{ item.id }}">
    <label class="slider_item_main_label">{{ item.name }}</label>
    <div  item="programm_{{ item.id }}" class="slider_arrow arrow_down"></div>
    <div class="slider_body" item="programm_{{ item.id }}">
        <table class="card width_700">
            <tr>
                <td class="attribute width_200 font16">Описание :</td><td class="font16">{{ item.description|default:"-" }}</td>
            </tr>
            <tr>
                <td class="attribute width_200 font16">Уровень :</td><td class="font16">{{ item.level_name|default:"-" }}</td>
            </tr>
            {% with institute_list=item.institute_list %}
            {% if institute_list %}
            <tr>
                <td class="attribute width_200 font16">Образовательные организации, реализующие программу :</td>
                <td>

                    <table class="card width_500">

                        {% for inst in institute_list %}
                        <tr>
                            <td><a href="{% url 'edu-institute' inst.item.institute.id %}">{{ inst.name }}</a></td>
                        </tr>
                        {% endfor %}

                    </table>
                </td>
            </tr>
            {% endif %}
            {% endwith %}

            {% if item.presentation %}
            <tr>
                <td class="attribute width_200 font16">Презентация :</td>
                <td><a href="{{ item.presentation_url }}">{{ item.presentation_filename }}</a></td>
            </tr>
            {% endif %}

        </table>

        <div class="clear"></div>
    </div>
    <div class="clear"></div>
</div>

templates/seminar_form.html
{% extends "personal_cabinet.html" %}

{% block jquery_ready %}

  $('#id_practic_begda').datepicker();
  $('#id_practic_endda').datepicker();

        if( $('#id_payment_method').val() != 'U' ){
            $('#id_details').closest(".row").css("display","none");
        }


  $('#id_payment_method').change(function(){

    if( $('#id_payment_method').val() != 'U' ){
      $('#id_details').closest(".row").css("display","none");
    }else{
      $('#id_details').closest(".row").css("display","block");
    }
    });

{% endblock %}

{% block include %}
<script type="text/javascript" src="/media/js/jquery-ui-1.8.18/development-bundle/ui/i18n/jquery.ui.datepicker-ru.js"></script>
<link rel="stylesheet" type="text/css" media="all" href="/media/css/cupertino/jquery-ui-1.8.18.custom.css" />

{% endblock %}

{% block caption %}
{% endblock %}

{% block slow_button_panel %}
{% endblock %}

{% block content %}

<div class="item">
    <div class="personal_card_header"><label>Заявка на семинар</label></div>
    <div class="personal_card_content stretchable">

        {% include 'errors_and_messages.html' %}
        <form id="newsform" action="{% url 'create_edu_request' %}" method="POST" class="editform" enctype="multipart/form-data">
		{% csrf_token %}

            <input type="hidden" name="institute_program" value="{{ institute_program.id }}">
            <input type="hidden" name="seminar" value="true">
            {% include 'form_loop.html' %}
            <div class="row last">
                <input type="submit" value="Подать заявку" />
            </div>
        </form>
    </div>
</div>
{% endblock %}

{% block right_button_panel %}
{% endblock %}