IPR/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.views.generic.base import RedirectView

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'IPR.views.home', name='home'),
    url(r'^favicon.ico$', RedirectView.as_view(url='/media/img/favicon_pnk.ico', permanent=True), name='favicon'),

    url(r'^simplimg/', include('simplimg.urls')),
    url(r'^olymp/', include('olymp.urls')),
    url(r'^edu/', include('education_programmes.urls')),
#    url(r'^mail/recovery/request/?$', 'IPR.views.mail_recovery_request',  name='mail-example-recovery-request'),
#    url(r'^mail2/?$', 'IPR.views.mail2',  name='mail-example-to'),
    url(r'^mail/?$', 'IPR.views.mail',  name='mail-example'),
    url(r'^mail2/?$', 'IPR.views.mail2',  name='mail-example-to'),

    url(r'^abc/?$', 'IPR.views.abc',  name='abc'),
    url(r'^abc2/?$', 'IPR.views.abc2',  name='abc-to'),

    url(r'^auth/notifications/?$', 'IPR.views.notifications',  name='notifications'),
    url(r'^auth/', include('common_user.urls')),
    #url(r'^todo/', include('todo.urls')),
    url(r'^msg/',include('user_messages.urls')),
	url(r'^ajax/region/statistic/(?P<raphael_slug>\w+)/?$','IPR.views.region_statistic', name='ajax_region_statistic'),

    url(r'^ajax/regions/?$','education_programmes.views.get_regions', name='ajax_get_regions'),
    url(r'^ajax/cities/?$','education_programmes.views.get_cities', name='ajax_get_cities'),
    url(r'^ajax/programs/?$','education_programmes.views.get_programm', name='ajax_get_programms'),
    url(r'^ajax/institutes/$','education_programmes.views.get_university', name='ajax_get_unvirsity_by_programm'),
    url(r'^ajax/has_seminar/$','education_programmes.views.get_seminar_attribute', name='ajax_seminar_attribute'),

    url(r'^archive/regions/?$',  'IPR.views.archive',  {'_type':'region'},    name='archive_regions'),
    url(r'^archive/cities/?$',   'IPR.views.archive',  {'_type':'city'},      name='archive_cities'),
    url(r'^archive/programs/?$', 'IPR.views.archive',  {'_type':'program'},   name='archive_programs'),
    url(r'^archive/institutes/$','IPR.views.archive',  {'_type':'institute'}, name='archive_unvirsity'),
    url(r'^archive/groups/$',    'IPR.views.archive',  {'_type':'group'},     name='archive_groups'),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/?', include(admin.site.urls)),
    url(r'^media/(?P<path>.*)$','django.views.static.serve', {'document_root': settings.PROJECT_ROOT + '/media/'}),
#    url(r'^favicon.ico$', RedirectView.as_view(url=settings.PROJECT_ROOT + '/media/images/favicon.ico')),

    url(r'^(?P<slug>[-\w\.]+)/?$','education_programmes.views.common_text', name='common-text-view'),
)

olymp/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls import patterns, include, url
from views import *
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

#from education_programmes.models import Education_Institute
#from education_programmes.forms import InstituteForm

urlpatterns = patterns('',
    # Examples:
#    url(r'^$', home, name='home'),

    url(r'^$', olymp, name='olymp'),
    url(r'^host/?$', host, name='host'),
    
    url(r'^tests/', include('olymp_tests.urls')),
    url(r'^people/', include('people.urls')),

    url(r'^content/(?P<id>\d+)/$', content, name='content-edit'),

    #url(r'^universities/(?P<limit>all|alone|\d+)/$', olymp_university_list, name='olymp-university-list'),
    
    url(r'^changepass/(\d+)/?$', customchangepass, name='olymp-changepass'),
    url(r'^login/?$', customlogin, name='olymp-login'), #'IPR.views.customlogin', name='login'),
    url(r'^logout/?$',customlogout, name='olymp-logout'), #'IPR.views.customlogout', name='logout'),
    # url(r'^olymp/', include('olymp.foo.urls')),

    url(r'^simplimg/', include('simplimg.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),


    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^media/(?P<path>.*)$','django.views.static.serve', {'document_root': settings.PROJECT_ROOT + '/media/olymp/'}),
    url(r'^static/(?P<path>.*)$','django.views.static.serve', {'document_root': settings.PROJECT_ROOT + '/static/'}),
)

olymp/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.forms import ModelForm
from django.contrib.auth import authenticate
from common_user.models import User
from olymp_tests.models import OlympContent
import sys


class OlympLoginForm(forms.Form):
    login = forms.CharField(max_length=30,label=u'Логин')
    password = forms.CharField(widget=forms.PasswordInput,label=u'Пароль')

    def clean(self):
        try:
            user = User.objects.get(username = self.cleaned_data.get('login'))
            user = authenticate(email = user.email,password = self.cleaned_data.get('password'))

            if user is None:
                self._errors["login"] = self.error_class([u'Логин или пароль некорректны'])
        except:
            self._errors["login"] = self.error_class([u'Логин или пароль некорректны'])

        return self.cleaned_data

class OlympContentForm(ModelForm):
    class Meta:
        model = OlympContent
        fields = ['content']

people/forms.py
# -*- coding: utf-8 -*-

from django import forms
from django.core import validators
from django.db.models import Q,Avg, Max, Min
from django.forms import ModelForm, Textarea
from django.forms.extras import * #SelectDateWidget
from models import *
from common_user.models import User
import sys,datetime

from django.conf import settings
from olymp.widgets import *

    
class UniversityRegisterForm(ModelForm):
    username  = forms.CharField(max_length=75, label=u'Логин')
    password1 = forms.CharField(widget=forms.PasswordInput,label=u'Пароль')
    password2 = forms.CharField(widget=forms.PasswordInput,label=u'Подтвердите пароль')
    
    class Meta:
        model = University
        fields = ['name','username','password1','password2','region','city','email','phone','rector_last_name','rector_first_name','rector_patronymic','curator_last_name','curator_first_name','curator_patronymic','curator_position']

    def clean(self):

        username = self.cleaned_data['username']

        if User.objects.filter(username=username).count():
            self._errors["username"] = self.error_class([u"пользователь с таким логином уже существует"])


        if (self.cleaned_data.get("password2", "") != self.cleaned_data.get("password1", "")):
            self._errors["password1"] = self.error_class([u"Пароли не совпадают."])
            #raise forms.ValidationError(u"Пароли не совпадают.")

        try:
            validators.validate_email(self.cleaned_data["email"])
        except:
            self._errors["email"] = self.error_class([u'Проверьте правильность ввода e-mail.'])

        return self.cleaned_data

class UniversityEditForm(ModelForm):
    class Meta:
        model = University
        fields = ['name','region','city','email','phone','rector_first_name','rector_last_name','rector_patronymic','curator_first_name','curator_last_name','curator_patronymic','curator_position']

    def clean(self):
        try:
            validators.validate_email(self.cleaned_data["email"])
        except:
            self._errors["email"] = self.error_class([u'Проверьте правильность ввода e-mail.'])

        return self.cleaned_data



#class StudentForm(ModelForm):
#    id                 = forms.IntegerField(required= False,label = u'ID')
#    must_delete        = forms.IntegerField(initial = 0,label = u'Удалить')
#    delete_checkbox    = forms.BooleanField(required= False,label=u'Удалить')
#
#    class Meta:
#        model = Question
#        fields = ['test','text','option1','option2','option3','option4','correct_option','number']
#
#        widgets = {
#            'test' : forms.HiddenInput(),
#            }
#
#    def __init__(self,*args, **kwargs):
#        super(QuestionForm, self).__init__(*args, **kwargs)
#        self.fields['must_delete'].widget = forms.HiddenInput()
#        self.fields['id'].widget = forms.HiddenInput()
#
#        if kwargs.has_key('instance'):
#            print  kwargs['instance'].id
#            self.fields['id'].initial = kwargs['instance'].id
#
#    def clean(self):
#        if self.cleaned_data.get("option1") == self.cleaned_data.get("option2"):
#            self._errors["option2"] = self.error_class([u'Вариант ответа не уникален!'])
#        if self.cleaned_data.get("option1") == self.cleaned_data.get("option3"):
#            self._errors["option3"] = self.error_class([u'Вариант ответа не уникален!'])
#        if self.cleaned_data.get("option1") == self.cleaned_data.get("option4"):
#            self._errors["option4"] = self.error_class([u'Вариант ответа не уникален!'])
#
#        if self.cleaned_data.get("option2") == self.cleaned_data.get("option3"):
#            self._errors["option3"] = self.error_class([u'Вариант ответа не уникален!'])
#        if self.cleaned_data.get("option2") == self.cleaned_data.get("option4"):
#            self._errors["option4"] = self.error_class([u'Вариант ответа не уникален!'])
#
#        if self.cleaned_data.get("option3") == self.cleaned_data.get("option4"):
#            self._errors["option4"] = self.error_class([u'Вариант ответа не уникален!'])
#        return self.cleaned_data



class OlympStudentShortForm(forms.Form):
    new_student_last_name          = forms.CharField(label = u'Фамилия', max_length=60)
    new_student_first_name           = forms.CharField(label = u'Имя', max_length=60)
    new_student_patronymic          = forms.CharField(label = u'Отчество', max_length=100)
    new_student_email               = forms.EmailField(label = u'Электронный адрес', max_length=100)
    new_student_birthday            = forms.DateField(label = u'Дата рождения')
    new_student_speciality          = forms.CharField(max_length=50,label = u'Направление')
    new_student_course              = forms.ChoiceField(choices=COURSE_CHOICES,label = u'Курс')
    new_student_finish_year         = forms.IntegerField(initial = 2014, label = u'Планируемый год выпуска')
    new_student_must_delete         = forms.IntegerField(initial = 0,label = u'Удалить')
    new_student_delete_checkbox     = forms.BooleanField(required= False,label=u'Удалить')

    def __init__(self,*args, **kwargs):
        super(OlympStudentShortForm, self).__init__(*args, **kwargs)
        self.fields['new_student_finish_year'].widget = forms.TextInput(attrs={'maxlength':4})
        self.fields['new_student_must_delete'].widget = forms.HiddenInput()
#        self.fields['new_student_birthday'].widget = DateWidget()


    def clean(self):
        try:
            validators.validate_email(self.cleaned_data["new_student_email"])
        except:
            self._errors["new_student_email"] = self.error_class([u'Проверьте правильность ввода e-mail.'])


#        if self.cleaned_data.get("new_question_option1") == self.cleaned_data.get("new_question_option2"):
#            self._errors["new_question_option2"] = self.error_class([u'Вариант ответа не уникален!'])
#        if self.cleaned_data.get("new_question_option1") == self.cleaned_data.get("new_question_option3"):
#            self._errors["new_question_option3"] = self.error_class([u'Вариант ответа не уникален!'])
#        if self.cleaned_data.get("new_question_option1") == self.cleaned_data.get("new_question_option4"):
#            self._errors["new_question_option4"] = self.error_class([u'Вариант ответа не уникален!'])
#
#        if self.cleaned_data.get("new_question_option2") == self.cleaned_data.get("new_question_option3"):
#            self._errors["new_question_option3"] = self.error_class([u'Вариант ответа не уникален!'])
#        if self.cleaned_data.get("new_question_option2") == self.cleaned_data.get("option4"):
#            self._errors["new_question_option4"] = self.error_class([u'Вариант ответа не уникален!'])
#
#        if self.cleaned_data.get("new_question_option3") == self.cleaned_data.get("new_question_option4"):
#            self._errors["new_question_option4"] = self.error_class([u'Вариант ответа не уникален!'])
        return self.cleaned_data


class OlympStudentForm(forms.ModelForm):
    id                 = forms.IntegerField(required= False,label = u'id')
    username           = forms.CharField(label = u'Логин', max_length=60)
    last_name         = forms.CharField(label = u'Фамилия', max_length=60)
    first_name          = forms.CharField(label = u'Имя', max_length=60)

    must_delete        = forms.IntegerField(initial = 0,label = u'Удалить')
    delete_checkbox    = forms.BooleanField(required= False,label=u'Удалить')

    class Meta:
        model = OlympStudent
        fields = ['user','id','username','detail','first_name','last_name','patronymic','email','birthday','speciality','course','finish_year']

        widgets = {
            'user' : forms.HiddenInput(),
            }

    def __init__(self,*args, **kwargs):
        super(OlympStudentForm, self).__init__(*args, **kwargs)
        self.fields['must_delete'].widget = forms.HiddenInput()
        self.fields['id'].widget = forms.HiddenInput()

        self.fields['username'].widget.attrs['readonly'] = True
        self.fields['detail'].widget.attrs['readonly'] = True

        if kwargs.has_key('instance'):
            print  kwargs['instance'].id
            self.fields['id'].initial = kwargs['instance'].id

            if kwargs['instance'].user is not None:
                self.fields['last_name'].initial = kwargs['instance'].user.last_name
                self.fields['first_name'].initial = kwargs['instance'].user.first_name
                self.fields['username'].initial = kwargs['instance'].user.username

    def clean(self):
        try:
            validators.validate_email(self.cleaned_data["email"])
        except:
            self._errors["email"] = self.error_class([u'Проверьте правильность ввода e-mail.'])

        return self.cleaned_data
		
class SoupForm(forms.Form):
    login = forms.CharField(max_length=30,label=u'Логин')
    password1 = forms.CharField(widget=forms.PasswordInput,label=u'Пароль')
    password2 = forms.CharField(widget=forms.PasswordInput,label=u'Подтвердите пароль')
    surname = forms.CharField(max_length=50,label=u'Фамилия')
    name = forms.CharField(max_length=50,label=u'Имя')

    def __init__(self, *args, **kwargs):
        super(SoupForm,self).__init__(*args, **kwargs)

    def clean(self):
        if (self.cleaned_data.get("password2", "") != self.cleaned_data.get("password1", "")):
            self._errors["password1"] = self.error_class([u"Пароли не совпадают."])
            raise forms.ValidationError(u"Пароли не совпадают.")

        try:
            login_exist = User.objects.get(username=self.cleaned_data["login"])
        except:
            login_exist = None
            #if email_exist is not None:
        if login_exist:
            self._errors["login"] = self.error_class([u'Такой пользователь уже зарегистрирован. Используйте другой, либо авторизуйтесь.'])
            raise forms.ValidationError(u'Такой пользователь уже зарегистрирован. Используйте другой, либо авторизуйтесь.')

templates/olymp/content.html
{% extends "olymp/palata_index.html" %}


{% block include %}

<script type="text/javascript" src="/media/tiny_mce/tiny_mce.js"></script>
 <script type="text/javascript">
        tinymce.init({
            mode: "textareas",
            theme: "advanced",
//            plugins: "advhr,table,emotions,media,insertdatetime,directionality",
            plugins : "autolink,lists,spellchecker,pagebreak,style,layer,table,save,advhr,simplimg,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template",

            // Theme options
            theme_advanced_buttons1 : "simplimg,save,newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,styleselect,formatselect,fontselect,fontsizeselect",
            theme_advanced_buttons2 : "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",
            theme_advanced_buttons3 : "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen",
            theme_advanced_buttons4 : "insertlayer,moveforward,movebackward,absolute,|,styleprops,spellchecker,|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking,template,blockquote,pagebreak,|,insertfile,insertimage",

            theme_advanced_toolbar_align: "left",
            theme_advanced_toolbar_location: "top",

//            theme_advanced_buttons1:"bold,italic,underline,strikethrough,sub,sup,separator,justifyleft,justifycenter,justifyright,justifyfull,separator,formatselect,fontselect,fontsizeselect,forecolor, visualchars",
//            theme_advanced_buttons2:"bullist,numlist,outdent,indent,ltr,rtl,separator,link,unlink,anchor,image,separator,table,insertdate,inserttime,advhr,emotions,media,charmap,separator,undo,redo",
//            theme_advanced_buttons3_add:"forecolor,backcolor,visualchars",


            theme_advanced_font_sizes:"170%,10px,11px,12px,13px,14px,15px,16px,17px,18px,19px,20px,21px,22px,23px,24px,25px,26px,27px,28px,29px,30px,32px,48px",
            height: "350px",
            width: "600px",
            convert_urls : false
        });
        </script>

{% endblock %}

{% block jquery_ready %}

{% endblock %}

{% block container %}

<div class="olymp_box">

    <div class="olymp_h1">{{ verbose_name }}</div>

    <form method="POST" action="{% url 'content-edit' current_id %}" class="item">

        {% csrf_token %}

        <ul>
            {% for field in Form %}
            <li >
                <div>
                    <label class="olymp_desc">{{ field.label }}{{ field.field.verbose_name }}</label>
                    <!--<input id="username" name="username" class="field text large" type="text" value=""/>-->
                    {{ field }}
                </div>
                {% if field.errors|length > 0 %}<div class="olymp_error_line">{{ field.errors }}</div>{% endif %}
            </li>
            {% endfor %}

            <li id="buttons">
                <input type="submit" id="saveForm" class="button" value="Сохранить">
                
                <div class="olymp_passing_button"><a href="/">Отмена</a></div>
            </li>
        </ul>
    </form>


</div><!-- box -->

{% endblock %}

templates/olymp/test_about.html
{% extends "olymp/palata_index.html" %}
{% load test_extra %}

{% block jquery %}


<!--$('#id_new_student_birthday').datepicker();-->

$('input').bind("keyup keypress", function(e) {
var code = e.keyCode || e.which;

if (code  == 13) {
e.preventDefault();
return false;
}
});

// добавляем студента
$('.addstudent').click(function(){

var dummy = $('li.olymp_complex#olymp_dummy').clone(true);

var count = parseInt($('input#new_student_count').val());
count = count + 1;

dummy.removeAttr('id');

$('li#buttons').before(dummy);
$('input#new_student_count').val(count);
var position = $('li#buttons').offset().top;
$(document).scrollTop(position);
return false;

});

$('input[name="new_student_delete_checkbox"]').click(function(){
if( $(this).is(":checked")){
$(this).closest('div').find('input[name="new_student_must_delete"]').val(1);
}else{
$(this).closest('div').find('input[name="new_student_must_delete"]').val(0);
}


});

$('input[name="delete_checkbox"]').click(function(){

if( $(this).is(":checked")){
$(this).closest('div').find('input[name="must_delete"]').val(1);
}else{
$(this).closest('div').find('input[name="must_delete"]').val(0);
}


});

{% endblock %}


{% block container %}

{% if user.is_univer and test|have_univer_request_on_test:user  %}
<div class="olymp_box">

    <div class="olymp_h1">Студенты</div>
    <div class="toolbar">
        <div class="olymp_passing_button"><a class="addstudent" href="#">Добавить студента</a></div>
         <div class="clear"></div>
    </div>

    <form method="POST" action="{% url 'test-about' test.id %}" class="olymp_item">

        <input id="new_student_count"  name="new_student_count" value="{{ new_student_count|default:0 }}" style="display: none">

        {% csrf_token %}

        <ul>

            {% for old_student_form in old_student_forms %}

            <li class="olymp_complex">
                <label class="olymp_desc">Студент</label>
                <div>

                    {% for field in old_student_form %}

                    {% if not field.is_hidden %}

    <span class="{% if field.name == 'email' or field.name == 'course' %}olymp_left{% endif %}{% if field.name == 'birthday' or field.name == 'finish_year' %}olymp_right{% endif %}{% if field.name == 'first_name' or field.name == 'last_name' or field.name == 'patronymic' or field.name == 'speciality'  %}olymp_full{% endif %}">
    <label class="olymp_desc">{{ field.label }}{{ field.field.verbose_name }}</label>
      {{ field }}
    {% if field.errors|length > 0 %}<div class="olymp_error_line">{{ field.errors }}</div>{% endif %}
    </span>

                    {% else %}
                    {{ field }}
                    {% endif %}

                    {% endfor %}

                </div>
            </li>
            {% endfor %}


            {% for new_student_form in new_student_forms %}

            <li class="olymp_complex">
                <label class="olymp_desc">Вопрос</label>
                <div>

                    {% for field in new_student_form %}

                    {% if not field.is_hidden %}

    <span class="{% if field.name == 'new_student_email' or field.name == 'new_student_course' %}olymp_left{% endif %}{% if field.name == 'new_student_birthday' or field.name == 'new_student_finish_year' %}olymp_right{% endif %}{% if field.name == 'new_student_first_name' or field.name == 'new_student_last_name' or field.name == 'new_student_patronymic' or field.name == 'new_student_speciality'  %}olymp_full{% endif %}">
    <label class="olymp_desc">{{ field.label }}{{ field.field.verbose_name }}</label>
      {{ field }}
    {% if field.errors|length > 0 %}<div class="olymp_error_line">{{ field.errors }}</div>{% endif %}
    </span>

                    {% else %}
                    {{ field }}
                    {% endif %}

                    {% endfor %}

                </div>
            </li>
            {% endfor %}


        <li id="buttons">
            <input type="submit" id="saveForm" class="button" value="Сохранить">
            
            <div class="olymp_passing_button"><a href="/" class="olymp_negative">Отмена</a></div>
            <div class="olymp_passing_button"><a href="#" class="addstudent">Добавить студента</a></div>
            <div class="clear"></div>
        </li>
        </ul>
    </form>

    <li class="olymp_complex" id="olymp_dummy" >
        <label class="olymp_desc">Студент</label>
        <div>
    {% for field in dummy_form %}

    {% if not field.is_hidden %}

    <span class="{% if field.name == 'new_student_email' or field.name == 'new_student_course' %}olymp_left{% endif %}{% if field.name == 'new_student_birthday' or field.name == 'new_student_finish_year' %}olymp_right{% endif %}{% if field.name == 'new_student_first_name' or field.name == 'new_student_last_name' or field.name == 'new_student_patronymic' or field.name == 'new_student_speciality'  %}olymp_full{% endif %}">
    <label class="olymp_desc">{{ field.label }}{{ field.field.verbose_name }}</label>
      {{ field }}
    {% if field.errors|length > 0 %}<div class="olymp_error_line">{{ field.errors }}</div>{% endif %}
    </span>

    {% else %}
       {{ field }}
    {% endif %}

    {% endfor %}
        </div>
        </li>


    <div class="clear"></div>

</div>

{% endif %}

{% endblock %}

templates/olymp/test_header.html
<div class="test_header">
    <h2>{{ test.name }}</h2>

    <ul>
        <li><h3>Время проведения</h3><div>с {{ test.begin|date:"d.m.Y" }} по {{ test.end|date:"d.m.Y" }}</div></li>

        <li><h3>Время регистрации</h3><div>с {{ test.begin_registration|date:"d.m.Y" }} по {{ test.end_registration|date:"d.m.Y" }}</div</li>

        <li><h3>Время на прохождение</h3><div>{{ test.max_time }}</div</li>
    </ul>

</div>

templates/olymp/test_participant.html
{% extends "olymp/palata_index.html" %}
{% load test_extra %}

{% block jquery %}


<!--$('#id_new_student_birthday').datepicker();-->

$('input').bind("keyup keypress", function(e) {
var code = e.keyCode || e.which;

if (code  == 13) {
e.preventDefault();
return false;
}
});

$('.addstudent').click(function(){

var dummy = $('li.olymp_complex#olymp_dummy').clone(true);

var count = parseInt($('input#new_student_count').val());
count = count + 1;

dummy.removeAttr('id');

$('li#buttons').before(dummy);
$('input#new_student_count').val(count);
return false;

});

$('input[name="new_student_delete_checkbox"]').click(function(){
if( $(this).is(":checked")){
$(this).closest('div').find('input[name="new_student_must_delete"]').val(1);
}else{
$(this).closest('div').find('input[name="new_student_must_delete"]').val(0);
}


});

$('input[name="delete_checkbox"]').click(function(){

if( $(this).is(":checked")){
$(this).closest('div').find('input[name="must_delete"]').val(1);
}else{
$(this).closest('div').find('input[name="must_delete"]').val(0);
}


});

$('a.a_olymp_univer_expand').click(function(){

   var  lv_class = 'ul.olymp_univer_participant[item="' + $(this).attr('item') + '"]';

   if( $('ul.olymp_univer_participant[item="' + $(this).attr('item') + '"]').is(":visible") ){

    $('ul.olymp_univer_participant[item="' + $(this).attr('item') + '"]').css("display","none");

        }else{

  if( $('ul.olymp_univer_participant[item="' + $(this).attr('item') + '"]').children('li').length == 0 ){

  $.get('/olymp/tests/test/participant/{{ item.id }}/' + $(this).attr('item') + '/', function (data) {
     console.log(data);

     $.each(data, function (i, data) {
       {% if user.is_authenticated and user.is_olympic and user.is_admin  %}

        $(lv_class).append("<li><div class='olymp_student_fio'>" + data.fio +  "</div><div class='olymp_student_edit'><a href='" + data.edit + "'>Редактировать</a></div><div class='olymp_student_delete'><a href='" + data.delete + "'>Удалить</a></div></li>");

       {% else %}

        $(lv_class).append("<li><strong>" + data.fio +  "</strong></li>");

        {% endif %}
     });
  });

  }

   $('ul.olymp_univer_participant[item="' + $(this).attr('item') + '"]').css("display","block");

        }
      return false;

});

{% endblock %}


{% block container %}

<div class="olymp_box">

    <div class="olymp_h1">Участники</div>
    
	<ul class="olymp_univers">
    {% for university in universities %}
     <li class="olymp_univer" item="{{ university.id }}">
         <div class="olymp_univer_row">
		 
		 <div class="olymp_univer_name">
		 <strong>{{ university.city }}</strong>.<strong>{{ university.name }}</strong>
         </div> 
		 
		 {% if user.is_authenticated and user.is_olympic and user.is_admin  %}
         <div class="olymp_univer_edit"><a href="{% url 'university-edit' university.id %}">Редактировать</a></div>
         <div class="olymp_univer_delete"><a href="{% url 'university-delete' university.id %}">Удалить</a></div>
		 {% endif %}
         {% if item|have_univer_student_on_test:university %}<div class="olymp_univer_expand" item="{{ university.id }}"><a class="a_olymp_univer_expand"  item="{{ university.id }}" href="{% url 'test-univer-participant' item.id university.id %}">Студенты</a></div>{% endif %}
         
		 <div class="clear"></div>
		 </div>
          
         <ul class="olymp_univer_participant"  item="{{ university.id }}" style="display:none">

             <div class="clear"></div>
         </ul>

     </li>


    {% endfor %}
        <div class="clear"></div>
        </ul>


    <div class="clear pillow"></div>


</div>

{% endblock %}